# Generated by Django 4.1.3 on 2023-01-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_admin_delete_hi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('t_id', models.IntegerField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='gymmem',
            name='phone',
            field=models.IntegerField(default=91, max_length=30),
        ),
    ]
