# Generated by Django 4.1.3 on 2023-01-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_gymmem_image_alter_trainer_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmem',
            name='image',
            field=models.ImageField(default='C:/Users/Ajay/Desktop/MAINgym/user-sign-icon-person-symbol-human-avatar-isolated-on-white-backogrund-vector.jpg', upload_to='myimage'),
        ),
    ]
