# Generated by Django 4.1.3 on 2023-01-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_alter_gymmem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmem',
            name='image',
            field=models.ImageField(default='user-sign-icon-person-symbol-human-avatar-isolated-on-white-backogrund-vector.jpg', upload_to='myimage'),
        ),
    ]
