# Generated by Django 4.1.3 on 2023-01-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0017_remove_gymmem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myimage'),
        ),
    ]
