# Generated by Django 4.1.3 on 2023-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0020_gymmem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmem',
            name='program',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
