# Generated by Django 4.1.3 on 2023-01-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_gymmem_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='t_id',
            field=models.CharField(max_length=30),
        ),
    ]
